"""Add illustrations and item_illustrations tables

Revision ID: 0d607c623452
Revises: 2352dfc009d9
Create Date: 2026-02-06 20:22:13.284685

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d607c623452"
down_revision: str | Sequence[str] | None = "2352dfc009d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "illustrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_illustrations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("illustration_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["illustration_id"],
            ["illustrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_item_illustrations_item_id_illustration_id",
        "item_illustrations",
        ["item_id", "illustration_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_item_illustrations_item_id_illustration_id", table_name="item_illustrations"
    )
    op.drop_table("item_illustrations")
    op.drop_table("illustrations")
    # ### end Alembic commands ###
