"""Add index on items text and language

Revision ID: 262cba6b5f6f
Revises: be45a8df7026
Create Date: 2026-01-23 09:00:35.428551

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "262cba6b5f6f"
down_revision: str | Sequence[str] | None = "be45a8df7026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_items_text_language", "items", ["text", "language"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_items_text_language", table_name="items")
    # ### end Alembic commands ###
