"""Add illustration_id to session_items

Revision ID: 322ec5502461
Revises: 4d559459f086
Create Date: 2026-02-09 21:46:52.921988

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "322ec5502461"
down_revision: str | Sequence[str] | None = "4d559459f086"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("illustration_id", sa.String(length=36), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_session_items_illustration_id",
            "illustrations",
            ["illustration_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # ### end Alembic commands ###

    # Backfill illustration_id for displayed items that have exactly one illustration
    conn = op.get_bind()
    conn.execute(
        sa.text("""
        UPDATE session_items
        SET illustration_id = (
            SELECT illustration_id
            FROM item_illustrations
            WHERE item_illustrations.item_id = session_items.item_id
        )
        WHERE displayed_at IS NOT NULL
        AND (
            SELECT COUNT(*)
            FROM item_illustrations
            WHERE item_illustrations.item_id = session_items.item_id
        ) = 1
    """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_items", schema=None) as batch_op:
        batch_op.drop_column("illustration_id")
    # ### end Alembic commands ###
