"""Make items text and language unique

Revision ID: 4d559459f086
Revises: 0d607c623452
Create Date: 2026-02-07 20:53:32.853429

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d559459f086"
down_revision: str | Sequence[str] | None = "0d607c623452"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_text_language"), table_name="items")
    op.create_index(
        "ix_items_text_language", "items", ["text", "language"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_items_text_language", table_name="items")
    op.create_index(
        op.f("ix_items_text_language"), "items", ["text", "language"], unique=False
    )
    # ### end Alembic commands ###
