"""Add starred to items

Revision ID: 6a23009b5b93
Revises: 2c853a2f65bf
Create Date: 2026-02-26 21:08:29.446896

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a23009b5b93"
down_revision: str | Sequence[str] | None = "2c853a2f65bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items",
        sa.Column("starred", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "starred")
    # ### end Alembic commands ###
